version: 2.1
orbs:
  node: circleci/node@1.1.6
  cypress: cypress-io/cypress@1.23.0
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install
            - run: yarn lint
  finalize-happo:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install
            - run: "HAPPO_NONCE=${CIRCLE_BUILD_NUM} node bin/happo-cypress.js finalize"
workflows:
  build-and-test:
    jobs:
      - build-and-test
  cypress:
    jobs:
      - cypress/run:
          yarn: true
          start: yarn dev
          command-prefix: node bin/happo-cypress.js -- yarn cypress run
  cypress-parallel:
    jobs:
      - cypress/install:
          yarn: true
      - cypress/run:
          requires:
            - cypress/install
          yarn: true
          start: yarn dev
          parallel: true
          parallelism: 2
          record: true
          command-prefix: "HAPPO_PROJECT=parallel HAPPO_NONCE=${CIRCLE_BUILD_NUM} node bin/happo-cypress.js -- yarn"
      - finalize-happo:
          requires:
            - cypress/run
