version: 2.1
orbs:
  node: circleci/node@1.1.6
  cypress: cypress-io/cypress@1.23.0
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install
            - run: yarn lint
workflows:
  build-and-test:
    jobs:
      - build-and-test
  cypress:
    jobs:
      - cypress/run:
          yarn: true
          start: yarn dev
          command: node bin/happo-cypress.js -- yarn cypress run
